/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_WPAN_H__
#define __ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_WPAN_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.NetworkManager.Device.Wpan */

#define NMDBUS_TYPE_DEVICE_WPAN (nmdbus_device_wpan_get_type ())
#define NMDBUS_DEVICE_WPAN(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NMDBUS_TYPE_DEVICE_WPAN, NMDBusDeviceWpan))
#define NMDBUS_IS_DEVICE_WPAN(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NMDBUS_TYPE_DEVICE_WPAN))
#define NMDBUS_DEVICE_WPAN_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), NMDBUS_TYPE_DEVICE_WPAN, NMDBusDeviceWpanIface))

struct _NMDBusDeviceWpan;
typedef struct _NMDBusDeviceWpan NMDBusDeviceWpan;
typedef struct _NMDBusDeviceWpanIface NMDBusDeviceWpanIface;

struct _NMDBusDeviceWpanIface
{
  GTypeInterface parent_iface;

  const gchar * (*get_hw_address) (NMDBusDeviceWpan *object);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NMDBusDeviceWpan, g_object_unref)
#endif

GType nmdbus_device_wpan_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *nmdbus_device_wpan_interface_info (void);
guint nmdbus_device_wpan_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus property accessors: */
const gchar *nmdbus_device_wpan_get_hw_address (NMDBusDeviceWpan *object);
gchar *nmdbus_device_wpan_dup_hw_address (NMDBusDeviceWpan *object);
void nmdbus_device_wpan_set_hw_address (NMDBusDeviceWpan *object, const gchar *value);


/* ---- */

#define NMDBUS_TYPE_DEVICE_WPAN_PROXY (nmdbus_device_wpan_proxy_get_type ())
#define NMDBUS_DEVICE_WPAN_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NMDBUS_TYPE_DEVICE_WPAN_PROXY, NMDBusDeviceWpanProxy))
#define NMDBUS_DEVICE_WPAN_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), NMDBUS_TYPE_DEVICE_WPAN_PROXY, NMDBusDeviceWpanProxyClass))
#define NMDBUS_DEVICE_WPAN_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), NMDBUS_TYPE_DEVICE_WPAN_PROXY, NMDBusDeviceWpanProxyClass))
#define NMDBUS_IS_DEVICE_WPAN_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NMDBUS_TYPE_DEVICE_WPAN_PROXY))
#define NMDBUS_IS_DEVICE_WPAN_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), NMDBUS_TYPE_DEVICE_WPAN_PROXY))

typedef struct _NMDBusDeviceWpanProxy NMDBusDeviceWpanProxy;
typedef struct _NMDBusDeviceWpanProxyClass NMDBusDeviceWpanProxyClass;
typedef struct _NMDBusDeviceWpanProxyPrivate NMDBusDeviceWpanProxyPrivate;

struct _NMDBusDeviceWpanProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  NMDBusDeviceWpanProxyPrivate *priv;
};

struct _NMDBusDeviceWpanProxyClass
{
  GDBusProxyClass parent_class;
};

GType nmdbus_device_wpan_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NMDBusDeviceWpanProxy, g_object_unref)
#endif

void nmdbus_device_wpan_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
NMDBusDeviceWpan *nmdbus_device_wpan_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
NMDBusDeviceWpan *nmdbus_device_wpan_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void nmdbus_device_wpan_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
NMDBusDeviceWpan *nmdbus_device_wpan_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
NMDBusDeviceWpan *nmdbus_device_wpan_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define NMDBUS_TYPE_DEVICE_WPAN_SKELETON (nmdbus_device_wpan_skeleton_get_type ())
#define NMDBUS_DEVICE_WPAN_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NMDBUS_TYPE_DEVICE_WPAN_SKELETON, NMDBusDeviceWpanSkeleton))
#define NMDBUS_DEVICE_WPAN_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), NMDBUS_TYPE_DEVICE_WPAN_SKELETON, NMDBusDeviceWpanSkeletonClass))
#define NMDBUS_DEVICE_WPAN_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), NMDBUS_TYPE_DEVICE_WPAN_SKELETON, NMDBusDeviceWpanSkeletonClass))
#define NMDBUS_IS_DEVICE_WPAN_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NMDBUS_TYPE_DEVICE_WPAN_SKELETON))
#define NMDBUS_IS_DEVICE_WPAN_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), NMDBUS_TYPE_DEVICE_WPAN_SKELETON))

typedef struct _NMDBusDeviceWpanSkeleton NMDBusDeviceWpanSkeleton;
typedef struct _NMDBusDeviceWpanSkeletonClass NMDBusDeviceWpanSkeletonClass;
typedef struct _NMDBusDeviceWpanSkeletonPrivate NMDBusDeviceWpanSkeletonPrivate;

struct _NMDBusDeviceWpanSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  NMDBusDeviceWpanSkeletonPrivate *priv;
};

struct _NMDBusDeviceWpanSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType nmdbus_device_wpan_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NMDBusDeviceWpanSkeleton, g_object_unref)
#endif

NMDBusDeviceWpan *nmdbus_device_wpan_skeleton_new (void);


G_END_DECLS

#endif /* __ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_WPAN_H__ */
