/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "org.freedesktop.NetworkManager.PPP.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  guint use_gvariant : 1;
  guint emits_changed_signal : 1;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.freedesktop.NetworkManager.PPP
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:NMDBusPPPManager
 * @title: NMDBusPPPManager
 * @short_description: Generated C code for the org.freedesktop.NetworkManager.PPP D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-freedesktop-NetworkManager-PPP.top_of_page">org.freedesktop.NetworkManager.PPP</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.freedesktop.NetworkManager.PPP ---- */

static const _ExtendedGDBusArgInfo _nmdbus_ppp_manager_method_info_need_secrets_OUT_ARG_username =
{
  {
    -1,
    (gchar *) "username",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _nmdbus_ppp_manager_method_info_need_secrets_OUT_ARG_password =
{
  {
    -1,
    (gchar *) "password",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _nmdbus_ppp_manager_method_info_need_secrets_OUT_ARG_pointers[] =
{
  &_nmdbus_ppp_manager_method_info_need_secrets_OUT_ARG_username.parent_struct,
  &_nmdbus_ppp_manager_method_info_need_secrets_OUT_ARG_password.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _nmdbus_ppp_manager_method_info_need_secrets =
{
  {
    -1,
    (gchar *) "NeedSecrets",
    NULL,
    (GDBusArgInfo **) &_nmdbus_ppp_manager_method_info_need_secrets_OUT_ARG_pointers,
    NULL
  },
  "handle-need-secrets",
  FALSE
};

static const _ExtendedGDBusArgInfo _nmdbus_ppp_manager_method_info_set_ip4_config_IN_ARG_config =
{
  {
    -1,
    (gchar *) "config",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _nmdbus_ppp_manager_method_info_set_ip4_config_IN_ARG_pointers[] =
{
  &_nmdbus_ppp_manager_method_info_set_ip4_config_IN_ARG_config.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _nmdbus_ppp_manager_method_info_set_ip4_config =
{
  {
    -1,
    (gchar *) "SetIp4Config",
    (GDBusArgInfo **) &_nmdbus_ppp_manager_method_info_set_ip4_config_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-ip4-config",
  FALSE
};

static const _ExtendedGDBusArgInfo _nmdbus_ppp_manager_method_info_set_ip6_config_IN_ARG_config =
{
  {
    -1,
    (gchar *) "config",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _nmdbus_ppp_manager_method_info_set_ip6_config_IN_ARG_pointers[] =
{
  &_nmdbus_ppp_manager_method_info_set_ip6_config_IN_ARG_config.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _nmdbus_ppp_manager_method_info_set_ip6_config =
{
  {
    -1,
    (gchar *) "SetIp6Config",
    (GDBusArgInfo **) &_nmdbus_ppp_manager_method_info_set_ip6_config_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-ip6-config",
  FALSE
};

static const _ExtendedGDBusArgInfo _nmdbus_ppp_manager_method_info_set_state_IN_ARG_state =
{
  {
    -1,
    (gchar *) "state",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _nmdbus_ppp_manager_method_info_set_state_IN_ARG_pointers[] =
{
  &_nmdbus_ppp_manager_method_info_set_state_IN_ARG_state.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _nmdbus_ppp_manager_method_info_set_state =
{
  {
    -1,
    (gchar *) "SetState",
    (GDBusArgInfo **) &_nmdbus_ppp_manager_method_info_set_state_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-state",
  FALSE
};

static const _ExtendedGDBusArgInfo _nmdbus_ppp_manager_method_info_set_ifindex_IN_ARG_ifindex =
{
  {
    -1,
    (gchar *) "ifindex",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const GDBusArgInfo * const _nmdbus_ppp_manager_method_info_set_ifindex_IN_ARG_pointers[] =
{
  &_nmdbus_ppp_manager_method_info_set_ifindex_IN_ARG_ifindex.parent_struct,
  NULL
};

static const _ExtendedGDBusMethodInfo _nmdbus_ppp_manager_method_info_set_ifindex =
{
  {
    -1,
    (gchar *) "SetIfindex",
    (GDBusArgInfo **) &_nmdbus_ppp_manager_method_info_set_ifindex_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-set-ifindex",
  FALSE
};

static const GDBusMethodInfo * const _nmdbus_ppp_manager_method_info_pointers[] =
{
  &_nmdbus_ppp_manager_method_info_need_secrets.parent_struct,
  &_nmdbus_ppp_manager_method_info_set_ip4_config.parent_struct,
  &_nmdbus_ppp_manager_method_info_set_ip6_config.parent_struct,
  &_nmdbus_ppp_manager_method_info_set_state.parent_struct,
  &_nmdbus_ppp_manager_method_info_set_ifindex.parent_struct,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _nmdbus_ppp_manager_interface_info =
{
  {
    -1,
    (gchar *) "org.freedesktop.NetworkManager.PPP",
    (GDBusMethodInfo **) &_nmdbus_ppp_manager_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "ppp-manager",
};


/**
 * nmdbus_ppp_manager_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-freedesktop-NetworkManager-PPP.top_of_page">org.freedesktop.NetworkManager.PPP</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
nmdbus_ppp_manager_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_nmdbus_ppp_manager_interface_info.parent_struct;
}

/**
 * nmdbus_ppp_manager_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #NMDBusPPPManager interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
nmdbus_ppp_manager_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * NMDBusPPPManager:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-NetworkManager-PPP.top_of_page">org.freedesktop.NetworkManager.PPP</link>.
 */

/**
 * NMDBusPPPManagerIface:
 * @parent_iface: The parent interface.
 * @handle_need_secrets: Handler for the #NMDBusPPPManager::handle-need-secrets signal.
 * @handle_set_ifindex: Handler for the #NMDBusPPPManager::handle-set-ifindex signal.
 * @handle_set_ip4_config: Handler for the #NMDBusPPPManager::handle-set-ip4-config signal.
 * @handle_set_ip6_config: Handler for the #NMDBusPPPManager::handle-set-ip6-config signal.
 * @handle_set_state: Handler for the #NMDBusPPPManager::handle-set-state signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-NetworkManager-PPP.top_of_page">org.freedesktop.NetworkManager.PPP</link>.
 */

typedef NMDBusPPPManagerIface NMDBusPPPManagerInterface;
G_DEFINE_INTERFACE (NMDBusPPPManager, nmdbus_ppp_manager, G_TYPE_OBJECT)

static void
nmdbus_ppp_manager_default_init (NMDBusPPPManagerIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * NMDBusPPPManager::handle-need-secrets:
   * @object: A #NMDBusPPPManager.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.NeedSecrets">NeedSecrets()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nmdbus_ppp_manager_complete_need_secrets() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-need-secrets",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NMDBusPPPManagerIface, handle_need_secrets),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * NMDBusPPPManager::handle-set-ip4-config:
   * @object: A #NMDBusPPPManager.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_config: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIp4Config">SetIp4Config()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nmdbus_ppp_manager_complete_set_ip4_config() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-ip4-config",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NMDBusPPPManagerIface, handle_set_ip4_config),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT);

  /**
   * NMDBusPPPManager::handle-set-ip6-config:
   * @object: A #NMDBusPPPManager.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_config: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIp6Config">SetIp6Config()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nmdbus_ppp_manager_complete_set_ip6_config() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-ip6-config",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NMDBusPPPManagerIface, handle_set_ip6_config),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT);

  /**
   * NMDBusPPPManager::handle-set-state:
   * @object: A #NMDBusPPPManager.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_state: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetState">SetState()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nmdbus_ppp_manager_complete_set_state() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-state",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NMDBusPPPManagerIface, handle_set_state),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT);

  /**
   * NMDBusPPPManager::handle-set-ifindex:
   * @object: A #NMDBusPPPManager.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_ifindex: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIfindex">SetIfindex()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nmdbus_ppp_manager_complete_set_ifindex() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-set-ifindex",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NMDBusPPPManagerIface, handle_set_ifindex),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_INT);

}

/**
 * nmdbus_ppp_manager_call_need_secrets:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.NeedSecrets">NeedSecrets()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nmdbus_ppp_manager_call_need_secrets_finish() to get the result of the operation.
 *
 * See nmdbus_ppp_manager_call_need_secrets_sync() for the synchronous, blocking version of this method.
 */
void
nmdbus_ppp_manager_call_need_secrets (
    NMDBusPPPManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "NeedSecrets",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nmdbus_ppp_manager_call_need_secrets_finish:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @out_username: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @out_password: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nmdbus_ppp_manager_call_need_secrets().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nmdbus_ppp_manager_call_need_secrets().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nmdbus_ppp_manager_call_need_secrets_finish (
    NMDBusPPPManager *proxy,
    gchar **out_username,
    gchar **out_password,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(ss)",
                 out_username,
                 out_password);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nmdbus_ppp_manager_call_need_secrets_sync:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @out_username: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @out_password: (out) (optional): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.NeedSecrets">NeedSecrets()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nmdbus_ppp_manager_call_need_secrets() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nmdbus_ppp_manager_call_need_secrets_sync (
    NMDBusPPPManager *proxy,
    gchar **out_username,
    gchar **out_password,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "NeedSecrets",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(ss)",
                 out_username,
                 out_password);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nmdbus_ppp_manager_call_set_ip4_config:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @arg_config: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIp4Config">SetIp4Config()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nmdbus_ppp_manager_call_set_ip4_config_finish() to get the result of the operation.
 *
 * See nmdbus_ppp_manager_call_set_ip4_config_sync() for the synchronous, blocking version of this method.
 */
void
nmdbus_ppp_manager_call_set_ip4_config (
    NMDBusPPPManager *proxy,
    GVariant *arg_config,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetIp4Config",
    g_variant_new ("(@a{sv})",
                   arg_config),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nmdbus_ppp_manager_call_set_ip4_config_finish:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nmdbus_ppp_manager_call_set_ip4_config().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nmdbus_ppp_manager_call_set_ip4_config().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nmdbus_ppp_manager_call_set_ip4_config_finish (
    NMDBusPPPManager *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nmdbus_ppp_manager_call_set_ip4_config_sync:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @arg_config: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIp4Config">SetIp4Config()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nmdbus_ppp_manager_call_set_ip4_config() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nmdbus_ppp_manager_call_set_ip4_config_sync (
    NMDBusPPPManager *proxy,
    GVariant *arg_config,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetIp4Config",
    g_variant_new ("(@a{sv})",
                   arg_config),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nmdbus_ppp_manager_call_set_ip6_config:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @arg_config: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIp6Config">SetIp6Config()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nmdbus_ppp_manager_call_set_ip6_config_finish() to get the result of the operation.
 *
 * See nmdbus_ppp_manager_call_set_ip6_config_sync() for the synchronous, blocking version of this method.
 */
void
nmdbus_ppp_manager_call_set_ip6_config (
    NMDBusPPPManager *proxy,
    GVariant *arg_config,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetIp6Config",
    g_variant_new ("(@a{sv})",
                   arg_config),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nmdbus_ppp_manager_call_set_ip6_config_finish:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nmdbus_ppp_manager_call_set_ip6_config().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nmdbus_ppp_manager_call_set_ip6_config().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nmdbus_ppp_manager_call_set_ip6_config_finish (
    NMDBusPPPManager *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nmdbus_ppp_manager_call_set_ip6_config_sync:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @arg_config: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIp6Config">SetIp6Config()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nmdbus_ppp_manager_call_set_ip6_config() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nmdbus_ppp_manager_call_set_ip6_config_sync (
    NMDBusPPPManager *proxy,
    GVariant *arg_config,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetIp6Config",
    g_variant_new ("(@a{sv})",
                   arg_config),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nmdbus_ppp_manager_call_set_state:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @arg_state: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetState">SetState()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nmdbus_ppp_manager_call_set_state_finish() to get the result of the operation.
 *
 * See nmdbus_ppp_manager_call_set_state_sync() for the synchronous, blocking version of this method.
 */
void
nmdbus_ppp_manager_call_set_state (
    NMDBusPPPManager *proxy,
    guint arg_state,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetState",
    g_variant_new ("(u)",
                   arg_state),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nmdbus_ppp_manager_call_set_state_finish:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nmdbus_ppp_manager_call_set_state().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nmdbus_ppp_manager_call_set_state().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nmdbus_ppp_manager_call_set_state_finish (
    NMDBusPPPManager *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nmdbus_ppp_manager_call_set_state_sync:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @arg_state: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetState">SetState()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nmdbus_ppp_manager_call_set_state() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nmdbus_ppp_manager_call_set_state_sync (
    NMDBusPPPManager *proxy,
    guint arg_state,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetState",
    g_variant_new ("(u)",
                   arg_state),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nmdbus_ppp_manager_call_set_ifindex:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @arg_ifindex: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIfindex">SetIfindex()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nmdbus_ppp_manager_call_set_ifindex_finish() to get the result of the operation.
 *
 * See nmdbus_ppp_manager_call_set_ifindex_sync() for the synchronous, blocking version of this method.
 */
void
nmdbus_ppp_manager_call_set_ifindex (
    NMDBusPPPManager *proxy,
    gint arg_ifindex,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "SetIfindex",
    g_variant_new ("(i)",
                   arg_ifindex),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nmdbus_ppp_manager_call_set_ifindex_finish:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nmdbus_ppp_manager_call_set_ifindex().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nmdbus_ppp_manager_call_set_ifindex().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nmdbus_ppp_manager_call_set_ifindex_finish (
    NMDBusPPPManager *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nmdbus_ppp_manager_call_set_ifindex_sync:
 * @proxy: A #NMDBusPPPManagerProxy.
 * @arg_ifindex: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIfindex">SetIfindex()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nmdbus_ppp_manager_call_set_ifindex() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nmdbus_ppp_manager_call_set_ifindex_sync (
    NMDBusPPPManager *proxy,
    gint arg_ifindex,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "SetIfindex",
    g_variant_new ("(i)",
                   arg_ifindex),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nmdbus_ppp_manager_complete_need_secrets:
 * @object: A #NMDBusPPPManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @username: Parameter to return.
 * @password: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.NeedSecrets">NeedSecrets()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nmdbus_ppp_manager_complete_need_secrets (
    NMDBusPPPManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *username,
    const gchar *password)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(ss)",
                   username,
                   password));
}

/**
 * nmdbus_ppp_manager_complete_set_ip4_config:
 * @object: A #NMDBusPPPManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIp4Config">SetIp4Config()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nmdbus_ppp_manager_complete_set_ip4_config (
    NMDBusPPPManager *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * nmdbus_ppp_manager_complete_set_ip6_config:
 * @object: A #NMDBusPPPManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIp6Config">SetIp6Config()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nmdbus_ppp_manager_complete_set_ip6_config (
    NMDBusPPPManager *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * nmdbus_ppp_manager_complete_set_state:
 * @object: A #NMDBusPPPManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetState">SetState()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nmdbus_ppp_manager_complete_set_state (
    NMDBusPPPManager *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * nmdbus_ppp_manager_complete_set_ifindex:
 * @object: A #NMDBusPPPManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-freedesktop-NetworkManager-PPP.SetIfindex">SetIfindex()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nmdbus_ppp_manager_complete_set_ifindex (
    NMDBusPPPManager *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * NMDBusPPPManagerProxy:
 *
 * The #NMDBusPPPManagerProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NMDBusPPPManagerProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NMDBusPPPManagerProxy.
 */

struct _NMDBusPPPManagerProxyPrivate
{
  GData *qdata;
};

static void nmdbus_ppp_manager_proxy_iface_init (NMDBusPPPManagerIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (NMDBusPPPManagerProxy, nmdbus_ppp_manager_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (NMDBusPPPManagerProxy)
                         G_IMPLEMENT_INTERFACE (NMDBUS_TYPE_PPP_MANAGER, nmdbus_ppp_manager_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (NMDBusPPPManagerProxy, nmdbus_ppp_manager_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (NMDBUS_TYPE_PPP_MANAGER, nmdbus_ppp_manager_proxy_iface_init))

#endif
static void
nmdbus_ppp_manager_proxy_finalize (GObject *object)
{
  NMDBusPPPManagerProxy *proxy = NMDBUS_PPP_MANAGER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (nmdbus_ppp_manager_proxy_parent_class)->finalize (object);
}

static void
nmdbus_ppp_manager_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
nmdbus_ppp_manager_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
nmdbus_ppp_manager_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_nmdbus_ppp_manager_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], NMDBUS_TYPE_PPP_MANAGER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, NMDBUS_TYPE_PPP_MANAGER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
nmdbus_ppp_manager_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  NMDBusPPPManagerProxy *proxy = NMDBUS_PPP_MANAGER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nmdbus_ppp_manager_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nmdbus_ppp_manager_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
nmdbus_ppp_manager_proxy_init (NMDBusPPPManagerProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = nmdbus_ppp_manager_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, NMDBUS_TYPE_PPP_MANAGER_PROXY, NMDBusPPPManagerProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), nmdbus_ppp_manager_interface_info ());
}

static void
nmdbus_ppp_manager_proxy_class_init (NMDBusPPPManagerProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = nmdbus_ppp_manager_proxy_finalize;
  gobject_class->get_property = nmdbus_ppp_manager_proxy_get_property;
  gobject_class->set_property = nmdbus_ppp_manager_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = nmdbus_ppp_manager_proxy_g_signal;
  proxy_class->g_properties_changed = nmdbus_ppp_manager_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (NMDBusPPPManagerProxyPrivate));
#endif
}

static void
nmdbus_ppp_manager_proxy_iface_init (NMDBusPPPManagerIface *iface)
{
}

/**
 * nmdbus_ppp_manager_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-NetworkManager-PPP.top_of_page">org.freedesktop.NetworkManager.PPP</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nmdbus_ppp_manager_proxy_new_finish() to get the result of the operation.
 *
 * See nmdbus_ppp_manager_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
nmdbus_ppp_manager_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (NMDBUS_TYPE_PPP_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.NetworkManager.PPP", NULL);
}

/**
 * nmdbus_ppp_manager_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nmdbus_ppp_manager_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nmdbus_ppp_manager_proxy_new().
 *
 * Returns: (transfer full) (type NMDBusPPPManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
NMDBusPPPManager *
nmdbus_ppp_manager_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return NMDBUS_PPP_MANAGER (ret);
  else
    return NULL;
}

/**
 * nmdbus_ppp_manager_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-NetworkManager-PPP.top_of_page">org.freedesktop.NetworkManager.PPP</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nmdbus_ppp_manager_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NMDBusPPPManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
NMDBusPPPManager *
nmdbus_ppp_manager_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (NMDBUS_TYPE_PPP_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.freedesktop.NetworkManager.PPP", NULL);
  if (ret != NULL)
    return NMDBUS_PPP_MANAGER (ret);
  else
    return NULL;
}


/**
 * nmdbus_ppp_manager_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like nmdbus_ppp_manager_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call nmdbus_ppp_manager_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See nmdbus_ppp_manager_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
nmdbus_ppp_manager_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (NMDBUS_TYPE_PPP_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.NetworkManager.PPP", NULL);
}

/**
 * nmdbus_ppp_manager_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nmdbus_ppp_manager_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nmdbus_ppp_manager_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type NMDBusPPPManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
NMDBusPPPManager *
nmdbus_ppp_manager_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return NMDBUS_PPP_MANAGER (ret);
  else
    return NULL;
}

/**
 * nmdbus_ppp_manager_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like nmdbus_ppp_manager_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nmdbus_ppp_manager_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NMDBusPPPManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
NMDBusPPPManager *
nmdbus_ppp_manager_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (NMDBUS_TYPE_PPP_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.freedesktop.NetworkManager.PPP", NULL);
  if (ret != NULL)
    return NMDBUS_PPP_MANAGER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * NMDBusPPPManagerSkeleton:
 *
 * The #NMDBusPPPManagerSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NMDBusPPPManagerSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NMDBusPPPManagerSkeleton.
 */

struct _NMDBusPPPManagerSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_nmdbus_ppp_manager_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  NMDBusPPPManagerSkeleton *skeleton = NMDBUS_PPP_MANAGER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], NMDBUS_TYPE_PPP_MANAGER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, NMDBUS_TYPE_PPP_MANAGER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_nmdbus_ppp_manager_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  NMDBusPPPManagerSkeleton *skeleton = NMDBUS_PPP_MANAGER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nmdbus_ppp_manager_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_nmdbus_ppp_manager_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  NMDBusPPPManagerSkeleton *skeleton = NMDBUS_PPP_MANAGER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nmdbus_ppp_manager_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _nmdbus_ppp_manager_skeleton_vtable =
{
  _nmdbus_ppp_manager_skeleton_handle_method_call,
  _nmdbus_ppp_manager_skeleton_handle_get_property,
  _nmdbus_ppp_manager_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
nmdbus_ppp_manager_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return nmdbus_ppp_manager_interface_info ();
}

static GDBusInterfaceVTable *
nmdbus_ppp_manager_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_nmdbus_ppp_manager_skeleton_vtable;
}

static GVariant *
nmdbus_ppp_manager_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  NMDBusPPPManagerSkeleton *skeleton = NMDBUS_PPP_MANAGER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_nmdbus_ppp_manager_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _nmdbus_ppp_manager_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _nmdbus_ppp_manager_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _nmdbus_ppp_manager_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.freedesktop.NetworkManager.PPP", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
nmdbus_ppp_manager_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void nmdbus_ppp_manager_skeleton_iface_init (NMDBusPPPManagerIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (NMDBusPPPManagerSkeleton, nmdbus_ppp_manager_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (NMDBusPPPManagerSkeleton)
                         G_IMPLEMENT_INTERFACE (NMDBUS_TYPE_PPP_MANAGER, nmdbus_ppp_manager_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (NMDBusPPPManagerSkeleton, nmdbus_ppp_manager_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (NMDBUS_TYPE_PPP_MANAGER, nmdbus_ppp_manager_skeleton_iface_init))

#endif
static void
nmdbus_ppp_manager_skeleton_finalize (GObject *object)
{
  NMDBusPPPManagerSkeleton *skeleton = NMDBUS_PPP_MANAGER_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (nmdbus_ppp_manager_skeleton_parent_class)->finalize (object);
}

static void
nmdbus_ppp_manager_skeleton_init (NMDBusPPPManagerSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = nmdbus_ppp_manager_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, NMDBUS_TYPE_PPP_MANAGER_SKELETON, NMDBusPPPManagerSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
nmdbus_ppp_manager_skeleton_class_init (NMDBusPPPManagerSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = nmdbus_ppp_manager_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = nmdbus_ppp_manager_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = nmdbus_ppp_manager_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = nmdbus_ppp_manager_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = nmdbus_ppp_manager_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (NMDBusPPPManagerSkeletonPrivate));
#endif
}

static void
nmdbus_ppp_manager_skeleton_iface_init (NMDBusPPPManagerIface *iface)
{
}

/**
 * nmdbus_ppp_manager_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-freedesktop-NetworkManager-PPP.top_of_page">org.freedesktop.NetworkManager.PPP</link>.
 *
 * Returns: (transfer full) (type NMDBusPPPManagerSkeleton): The skeleton object.
 */
NMDBusPPPManager *
nmdbus_ppp_manager_skeleton_new (void)
{
  return NMDBUS_PPP_MANAGER (g_object_new (NMDBUS_TYPE_PPP_MANAGER_SKELETON, NULL));
}

