#define BINDIR "/usr/local/bin"
#define DATADIR "/usr/local/share"
#define LIBEXECDIR "/usr/local/libexec"
#define LOCALSTATEDIR "/var/local"
#define NMCONFDIR "/usr/local/etc/NetworkManager"
#define NMLIBDIR "/usr/local/lib/NetworkManager"
#define NMLOCALEDIR "/usr/local/share/locale"
#define NMPLUGINDIR "/usr/local/lib/x86_64-linux-gnu/NetworkManager/1.36.4"
#define NMRUNDIR "/var/local/run/NetworkManager"
#define NMSTATEDIR "/var/local/lib/NetworkManager"
#define NMVPNDIR "/usr/local/lib/x86_64-linux-gnu/NetworkManager"
#define NM_BUILD_BUILDDIR "/home/zsirost/projects/Network-Manager-git/NetworkManager/builddir"
#define NM_BUILD_SRCDIR "/home/zsirost/projects/Network-Manager-git/NetworkManager"
/* #undef PPPD_PLUGIN_DIR */
#define PREFIX "/usr/local"
#define RUNSTATEDIR "/var/local/run"
#define SYSCONFDIR "/usr/local/etc"
